# Banco de dados
spring.datasource.url=jdbc:mysql://mysql-32b6936c-inf-3c7b.l.aivencloud.com:17991/defaultdb?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Servidor
server.port=8080

# Serialização de datas ISO
spring.jackson.serialization.write-dates-as-timestamps=false
